import type { Metadata } from "next";
import { Inter, Waterfall } from "next/font/google";
import "./globals.css";
import { AppWrapper } from "@/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <AppWrapper>
          <body className={inter.className}>{children}</body>
        </AppWrapper>
    </html>
  );
}
